services:

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://root:root@mongodb:27017/blood-manager?authSource=admin
      secret_key: guiyfgc837tgf3iw87-012389764
      environment: development
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: blood-manager
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo/initdb:/docker-entrypoint-initdb.d:ro

  mongo-express:
    image: mongo-express:1.0.2-20
    restart: always
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8888:8081"

volumes:
  mongo-data:
